# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detectable_ppm', models.IntegerField()),
                ('detectable_substance', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_text', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('varietal', models.CharField(blank=True, max_length=100, null=True)),
                ('process', models.CharField(blank=True, max_length=100, null=True)),
                ('tasting_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('roast_date', models.DateField()),
                ('brew_date', models.DateField()),
                ('test_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryFlavor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='roasters')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryFlavor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chemical_compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee.Chemical')),
                ('parent_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.PrimaryFlavor')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('completed', models.DateTimeField(verbose_name='Completed')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TertiaryFlavor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chemical_compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Chemical')),
                ('parent_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.SecondaryFlavor')),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='roaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Roaster'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.SurveyResult'),
        ),
    ]
