# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detectable_ppm', models.IntegerField()),
                ('detectable_substance', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryFlavor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryFlavor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chemical_compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Chemical')),
                ('parent_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.PrimaryFlavor')),
            ],
        ),
        migrations.CreateModel(
            name='TertiaryFlavor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chemical_compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Chemical')),
                ('parent_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.SecondaryFlavor')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
