# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20160501_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
