# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_auto_20160501_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
