# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_brewmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('grams_coffee', models.IntegerField()),
                ('grams_water', models.IntegerField()),
                ('water_temp', models.IntegerField(blank=True, null=True)),
                ('grind', models.CharField(max_length=200)),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='seconds')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Coffee')),
            ],
        ),
        migrations.AlterField(
            model_name='brewmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='brew',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.BrewMethod'),
        ),
    ]
