# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_coffee_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='region',
            new_name='origin',
        ),
        migrations.AlterField(
            model_name='coffee',
            name='tasting_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
