# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_auto_20160518_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AlterField(
            model_name='brew',
            name='grind',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
