# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_auto_20160429_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
