# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_auto_20160528_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='secondaryflavor',
            name='chemical_compound',
        ),
        migrations.RemoveField(
            model_name='tertiaryflavor',
            name='chemical_compound',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee.Question'),
        ),
        migrations.AddField(
            model_name='brew',
            name='initial_score',
            field=models.IntegerField(default=-1),
        ),
    ]
