# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_auto_20160531_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='detectable_ppm',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='detectable_substance',
        ),
        migrations.AddField(
            model_name='chemical',
            name='primary_sensory',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='chemical',
            name='secondary_sencory',
            field=models.CharField(default='', max_length=500),
        ),
    ]
