# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_auto_20160531_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='primary_sensory',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='secondary_sencory',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
