# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0011_auto_20160531_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemical',
            old_name='secondary_sencory',
            new_name='secondary_sensory',
        ),
    ]
