# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0012_auto_20160531_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='descriptors',
            field=models.CharField(default='', max_length=200),
        ),
    ]
