# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_chemical_descriptors'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='descriptors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
