# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_coffee_descriptors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='descriptors',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
