# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0017_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee.Coffee'),
        ),
    ]
