# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 04:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0021_auto_20160604_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 4, 21, 19, 45, 664826), null=True),
        ),
    ]
